// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Chronokeep.IO.HtmlTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Chronokeep;
    using Chronokeep.Objects;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class HtmlPrintableTemplate : HtmlPrintableTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"

/*
Chronokeep Desktop - Race Scoring Software
Copyright (C) 2026 James Sentinella

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

            
            #line default
            #line hidden
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n<!doctype html>\n<html lang=\"en\">\n\t<head>\n\t\t<meta charset=\"UTF-8\">\n\t\t<link rel=\'s" +
                    "tylesheet\' href=\'css/bootstrap.min.css\'>\n\t\t<link rel=\'stylesheet\' href=\'css/styl" +
                    "e.min.css\'>\n\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1" +
                    ".0\">\n\t\t<title>");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.PrettyParticipantName));
            
            #line default
            #line hidden
            this.Write("</title>\n\t\t<style>\n\t\t\t@font-face {\n\t\t\t\tfont-family: \"Roboto\";\n\t\t\t\tsrc: url(\'fonts" +
                    "/Roboto_Condensed-Regular.ttf\');\n\t\t\t}\n\t\t\t.roboto {\n\t\t\t\tfont-family: \"Roboto\";\n\t\t" +
                    "\t}\n\t\t\t.divider {\n\t\t\t\theight: 2px;\n\t\t\t\tbackground-color: black;\n\t\t\t\tmax-width: ");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ScaledDividerWidth()));
            
            #line default
            #line hidden
            this.Write("px;\n\t\t\t}\n\t\t\t.min-col {\n\t\t\t\twidth: ");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ScaledColumnWidth()));
            
            #line default
            #line hidden
            this.Write("px;\n\t\t\t}\n\t\t\t.d-1 {\n\t\t\t\tfont-size: ");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ScaledTextOne()));
            
            #line default
            #line hidden
            this.Write("rem;\n\t\t\t}\n\t\t\t.d-2 {\n\t\t\t\tfont-size: ");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ScaledTextTwo()));
            
            #line default
            #line hidden
            this.Write("rem;\n\t\t\t}\n\t\t\t.main {\n\t\t\t\tmargin-left: ");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LeftMargin));
            
            #line default
            #line hidden
            this.Write("px;\n\t\t\t\tmargin-top: ");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TopMargin));
            
            #line default
            #line hidden
            this.Write("px;\n\t\t\t\twidth: ");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ScaledTotalWidth()));
            
            #line default
            #line hidden
            this.Write("px;\n\t\t\t}\n\t\t\t.img {\n\t\t\t\theight:");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ScaledImageHeight()));
            
            #line default
            #line hidden
            this.Write(@"px;
			}
		</style>
	</head>
	<body>
		<div class=""main"">
			<div class=""row p-1 justify-content-center align-content-center"">
				<div class=""col-auto img"">
					<img class=""img"" src=""images/boston.png"" style=""display:block;margin-left:auto;"">
				</div>
				<div class=""col-auto"">
					<div class=""roboto text-center d-2 m-0 mt-3"">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.DistanceName));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t\t<div class=\"roboto text-center d-1 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.PrettyParticipantName));
            
            #line default
            #line hidden
            this.Write(@"</div>
				</div>
				<div class=""col-auto img"">
					<img class=""img"" src=""images/personal.png"">
				</div>
			</div>
			<div class=""row p-2 justify-content-center align-content-center"">
				<div class=""col-auto min-col"">
					<div class=""roboto text-center d-2 m-0"">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.ChipTime[..(result.ChipTime.Length > 3 ? result.ChipTime.Length -2 : result.ChipTime.Length)]));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t\t<div class=\"roboto text-center d-2 m-0\">Time</div>\n\t\t\t\t</div>\n\t\t\t\t<di" +
                    "v class=\"col-auto min-col\">\n\t\t\t\t\t<div class=\"roboto text-center d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(distanceValue));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t\t<div class=\"roboto text-center d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(distanceValueStr));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t</div>\n\t\t\t\t<div class=\"col-auto min-col\">\n\t\t\t\t\t<div class=\"roboto text" +
                    "-center d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pace));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t\t<div class=\"roboto text-center d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(paceStr));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t\t<div class=\"row p-1 justify-content-center align-c" +
                    "ontent-center\">\n\t\t\t\t<div class=\"col-auto min-col\">\n\t\t\t\t\t<div class=\"roboto text-" +
                    "center d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.Place));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t\t<div class=\"divider mx-auto\"></div>\n\t\t\t\t\t<div class=\"roboto text-cent" +
                    "er d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(numOverall));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t\t<div class=\"roboto text-center d-2 m-0\">Overall</div>\n\t\t\t\t</div>\n\t\t\t\t" +
                    "<div class=\"col-auto min-col\">\n\t\t\t\t\t<div class=\"roboto text-center d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.GenderPlace));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t\t<div class=\"divider mx-auto\"></div>\n\t\t\t\t\t<div class=\"roboto text-cent" +
                    "er d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(numGender));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t\t<div class=\"roboto text-center d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenderStr));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t</div>\n\t\t\t\t<div class=\"col-auto min-col\">\n\t\t\t\t\t<div class=\"roboto text" +
                    "-center d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.AgePlace));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t\t<div class=\"divider mx-auto\"></div>\n\t\t\t\t\t<div class=\"roboto text-cent" +
                    "er d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(numAgeGroup));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t\t<div class=\"roboto text-center d-2 m-0\">");
            
            #line 1 "D:\Chronokeep\desktop\Chronokeep\IO\HtmlTemplates\HtmlPrintableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AgeGroupStr));
            
            #line default
            #line hidden
            this.Write("</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t</body>\n</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class HtmlPrintableTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
