# This is a continuous delivery pipeline for github meant to deploy Chronokeep whenever a tag is pushed.
#
name: Chronokeep Continuous Delivery

on:
  workflow_dispatch:

  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      # Continue running other matrix jobs even if one fails.
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            architecture: ['Any CPU', 'x64']
            app_packages_archive: chronokeep-setup.exe
            app_zip_archive: chronokeep.zip
          - os: ubuntu-latest
            architecture: ['Any CPU', 'x64']
            app_packages_archive: chronokeep.tar.gz
            app_zip_archive: chronokeep.tar
    runs-on: ${{ matrix.os }}

    env:
      SigningCertificate: Chronokeep\Chronokeep.pfx
      Solution_Path: Chronokeep.sln
      Compile_Path: Chronokeep\bin\Release\net10.0
      Version_Path: Chronokeep\version.txt
      Actions_Allow_Unsecure_Commands: true # Allows AddPAth and SetEnv commands

    steps:
    - name: Display build info
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "Arch: ${{ matrix.architecture }}"

    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-tags: true

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v5.3.0
      with:
        dotnet-version: '10.x'

    # Add  MsBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v3

    # Setup Nuget to restore packages
    - name: Setup Nuget
      uses: Nuget/setup-nuget@v3

    # Restore Nuget Packages
    - name: Restore Nuget Packages
      run: nuget restore $env:Solution_Path

    # Generate version text file because msbuild isn't generating it properly
    - name: Generate version text file
      run: git describe --tag > $env:Version_Path

    # Build the app for Release
    - name: Build program
      run: msbuild $env:Solution_Path /p:Platform="Any CPU" /p:Configuration=Release

    # Set an environment variable to the tag we want to use to describe this release.
    - name: Get tag environment variable.
      run: echo "RELEASE_VERSION=$(git describe --tag)" >> $GITHUB_OUTPUT
      id: release-version

    # Run Inno Setup
    - name: Create setup with Inno Setup
      run: .\Inno\ISCC.exe /DMyAppVersion=${{ steps.release-version.outputs.RELEASE_VERSION }} /DMyAppDirectory=$env:Compile_Path /O$env:Compile_Path /SCompression=bzip2 .\install-script.iss

    # Create zip
    - name: Create zip of all files.
      run: Compress-Archive -Path $env:Compile_Path\* -Destination $env:Compile_Path\$env:App_Zip_Archive

    # Create the release
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag: ${{ steps.release-version.outputs.RELEASE_VERSION }}

    # Upload installer
    - name: Update installer
      id: upload-installer
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.Compile_Path }}\${{ matrix.app_packages_archive }}

      
    # Upload archive
    - name: Update archive
      id: upload-archive
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.Compile_Path }}\${{ matrix.app_zip_archive }}